config/routes.rb
Rails.application.routes.draw do

  get 'pages/index'
  post 'pages/create'
  namespace :admin do
    resources :articles
    resources :article_categories
  end
  # mount Fae below your admin namespec
  mount Fae::Engine => '/admin'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  include Fae::BaseModelConcern
  has_fae_file :pdf

  has_fae_image :hero_image

  def fae_display_field
    title
  end

  belongs_to :article_category
end

app/models/article_category.rb
class ArticleCategory < ApplicationRecord
  include Fae::BaseModelConcern

  acts_as_list add_new_at: :top
  default_scope { order(:position) }

  def fae_display_field
    name
  end

end

app/models/article_image.rb
class ArticleImage < ApplicationRecord
  mount_uploader :image, ImageUploader
end

app/models/article_page.rb
class ArticlePage < Fae::StaticPage

  @slug = 'article'

  # required to set the has_one associations, Fae::StaticPage will build these associations dynamically
  def self.fae_fields
    {
      body: { type: Fae::TextArea }
    }
  end

end

app/models/concerns/fae/authorization_concern.rb
module Fae
  module AuthorizationConcern
    extend ActiveSupport::Concern
    module ClassMethods

      # Use the access_map to define any controllers that need any special authorization
      # Fae comes with three default roles:
      # - super admin: CRUD all objects, INCLUDING users and root settings
      # - admin: CRUD all objects, INCLUDING users and EXCLUDING root settings
      # - users: CRUD all objects, EXCLUDING users and root settings

      # each item should have a string key of the plural controller name and
      # an array of role names for the value
      # use "content_blocks/#{page_name}" for content blocks

      # example:
      # {
      #  'people' => ['super admin', 'admin'],
      #  'content_blocks/about_us' => ['super admin']
      # }
      def access_map
        {}
      end

    end
  end
end

app/models/concerns/fae/navigation_concern.rb
module Fae
  module NavigationConcern
    extend ActiveSupport::Concern

    # define the navigation structure in this file
    # example structure:
    #
    # def structure
    #   [
    #     item('Top Nav Item 1', subitems: [
    #       item('Top Nav Dropdown Item 1', class: 'custom-class', path: some_named_route_path),
    #       item('Top Nav Dropdown Item 2', subitems: [
    #         item('Side Nav Item 1', subitems: [
    #           item('Side Nav Nested Item', path: some_named_route_path)
    #         ]),
    #         item('Side Nav Item 1', path: some_named_route_path)
    #       ]),
    #     ]),
    #     item('Pages', subitems: [
    #       item('Home', path: fae.edit_content_block_path('home')),
    #       item('About Us', path: fae.edit_content_block_path('about_us'))
    #     ])
    #   ]
    # end

    def structure
      [
        item('Article Categories', path: admin_article_categories_path),
        item('Articles', path: admin_articles_path),
        # scaffold inject marker
      ]
    end

  end
end

app/controllers/admin/article_categories_controller.rb
module Admin
  class ArticleCategoriesController < Fae::BaseController

  end
end

app/controllers/admin/articles_controller.rb
module Admin
  class ArticlesController < Fae::BaseController

    private

    def build_assets
      @item.build_hero_image if @item.hero_image.blank?
      @item.build_pdf if @item.pdf.blank?
    end

  end
end

app/controllers/admin/content_blocks_controller.rb
module Admin
  class ContentBlocksController < Fae::StaticPagesController

    private

    def fae_pages
      [ArticlePage]
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  protect_from_forgery prepend: true
  # skip_before_action :verify_authenticity_token, only: [:cretae]

  def index
    @article = Article.first
  end

  def create
    article_image = ArticleImage.new
    article_image.image = params[:file]
    article_image.save

    article_image.reload

    render json: {location: "http://localhost:3000#{article_image.image.url}" }
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/admin/article_categories/_form.html.slim
= simple_form_for(['admin', @item]) do |f|
  == render 'fae/shared/form_header', header: @klass_name

  main.content
    = fae_input f, :name

app/views/admin/article_categories/edit.html.slim
== render 'form'

app/views/admin/article_categories/index.html.slim
== render 'fae/shared/index_header', title: @klass_humanized.pluralize.titleize

main.content
  table.js-sort-row
    thead
      tr
        th.th-sortable-handle
        th Name
        th.-action-wide Modified
        th.-action data-sorter="false"

    tbody
      - if @items.present?
        - @items.each do |item|
          tr id=fae_sort_id(item)
            td.sortable-handle: i.icon-sort
            td = link_to item.fae_display_field, edit_admin_article_category_path(item)
            td = fae_date_format item.updated_at
            td = fae_delete_button item
      - else
        tr: td colspan="4" No items found

app/views/admin/article_categories/new.html.slim
== render 'form'

app/views/admin/articles/_form.html.slim
= javascript_include_tag "https://cloud.tinymce.com/5/tinymce.min.js?apiKey=9r34rgbfjm7zeisnh1m647ax6k9xv36r1cadjszz8j7olchz"
javascript:
  tinymce.init({ 
    selector:'#article_body',
    menubar:false,
    plugins: "table, image, media, link imagetools",
    toolbar: "undo redo | formatselect | bold italic backcolor | table | image | media | link",
    imagetools_toolbar: "rotateleft rotateright | flipv fliph | editimage imageoptions",
    images_upload_url: '/pages/create',
    automatic_uploads: false,
    images_reuse_filename: true
  });

= simple_form_for(['admin', @item]) do |f|
  == render 'fae/shared/form_header', header: @klass_name

  main.content
    = fae_input f, :title
    = fae_input f, :slug
    = fae_input f, :introduction
    = fae_input f, :body
    = fae_input f, :date

    = fae_association f, :article_category

    = fae_image_form f, :hero_image
    = fae_file_form f, :pdf

app/views/admin/articles/edit.html.slim
== render 'form'

app/views/admin/articles/index.html.slim
== render 'fae/shared/index_header', title: @klass_humanized.pluralize.titleize

main.content
  table.js-sort-column
    thead
      tr
        th Title
        th.-action-wide Modified
        th.-action data-sorter="false"

    tbody
      - if @items.present?
        - @items.each do |item|
          tr id=fae_sort_id(item)
            td = link_to item.fae_display_field, edit_admin_article_path(item)
            td = fae_date_format item.updated_at
            td = fae_delete_button item
      - else
        tr: td colspan="3" No items found

app/views/admin/articles/new.html.slim
== render 'form'

app/views/admin/content_blocks/article.html.slim
= simple_form_for @item, url: fae.update_content_block_path(slug: @item.slug), method: :put do |f|
  == render 'fae/shared/form_header', header: @item

  main.content
    = fae_input f, :title

    = fae_content_form f, :body

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ReinteractiveCms</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pages/index.html.erb
<%= raw @article.body  %>